---
- name: Install and Configure Prometheus
  hosts: prometheus
  become: yes
  user: prometheus
  vars:
    prometheus_version: "2.52.0"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    prometheus_home: "/etc/prometheus"
    prometheus_storage_dir: "/var/lib/prometheus"
    prometheus_binary_dir: "/usr/local/bin"

  tasks:
    - name: Update apt cache and Upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - tar
        - wget

    - name: Create Prometheus user and group
      user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        system: yes
        createhome: no

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      loop:
        - "{{ prometheus_home }}"
        - "{{ prometheus_storage_dir }}"

    - name: Download Prometheus binaries
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
        mode: '0644'

    - name: Extract Prometheus binaries
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp"
        remote_src: yes
        extra_opts: [--strip-components=1]
      notify: restart prometheus

    - name: Move Prometheus binaries to /usr/local/bin
      command: mv /tmp/prometheus {{ prometheus_binary_dir }}/prometheus
      args:
        creates: "{{ prometheus_binary_dir }}/prometheus"
      notify: restart prometheus

    - name: Move promtool binaries to /usr/local/bin
      command: mv /tmp/promtool {{ prometheus_binary_dir }}/promtool
      args:
        creates: "{{ prometheus_binary_dir }}/promtool"
      notify: restart prometheus

    - name: Copy Prometheus configuration files
      template:
        src: "prometheus.yml.j2"
        dest: "{{ prometheus_home }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      notify: restart prometheus

    - name: Create Prometheus systemd service file
      copy:
        dest: "/etc/systemd/system/prometheus.service"
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_group }}
          Type=simple
          ExecStart={{ prometheus_binary_dir }}/prometheus \
            --config.file={{ prometheus_home }}/prometheus.yml \
            --storage.tsdb.path={{ prometheus_storage_dir }} \
            --web.console.templates={{ prometheus_home }}/consoles \
            --web.console.libraries={{ prometheus_home }}/console_libraries
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: restart prometheus


    - name: Ensure Prometheus service is running
      systemd:
        name: prometheus
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
        daemon_reload: yes

