- name: Install Node Exporter
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.8.0"

  tasks:
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
        mode: '0644'

    - name: Create Node Exporter directory
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/opt"
        remote_src: yes
        creates: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64"

    - name: Create symlink to Node Exporter binary
      file:
        src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        state: link

    - name: Create Node Exporter systemd service file
      copy:
        dest: "/etc/systemd/system/node_exporter.service"
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=nobody
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes


